# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               轴(jiāo hù)
tagline:             体验与实现，交互与交流
url:                 http://uxzone.org
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Li Chong
  url:               https://github.com/delapecci
  email:             chong.li@uxzone.org

# Custom vars
#version:             1.0.0
#github:
#  repo:              https://github.com/poole/poole
